import os
import re

def generate_soc_package(source_dir, output_filename="soc_package.sv", package_name="soc_package"):
    """
    Scans a directory for SystemVerilog files and creates a unified compilation package.
    """
    if not os.path.exists(source_dir):
        print(f"Error: Directory '{source_dir}' does not exist.")
        return

    sv_files = []
    
    # Walk through the directory to find all SystemVerilog files
    for root, _, files in os.walk(source_dir):
        for file in files:
            if file.endswith(('.sv', '.svh')):
                # Skip the package file itself if it already exists in the folder
                if file == output_filename:
                    continue
                
                # Get the relative path from the source directory to preserve structure
                rel_path = os.path.relpath(os.path.join(root, file), source_dir)
                # Normalise paths to use forward slashes (best practice for EDA tools)
                rel_path = rel_path.replace("\\", "/")
                sv_files.append(rel_path)

    if not sv_files:
        print(f"No SystemVerilog files found in '{source_dir}'.")
        return

    # Sort files to ensure dependencies compile in the correct order:
    # 1. Base interfaces/types/packages first (.svh or files containing 'pkg'/'cfg')
    # 2. Components and sequences later
    def compilation_priority(filename):
        lower_name = filename.lower()
        if "pkg" in lower_name or "defines" in lower_name:
            return (0, filename)  # Highest priority
        if filename.endswith(".svh"):
            return (1, filename)  # High priority headers
        if "cfg" in lower_name or "config" in lower_name:
            return (2, filename)  # Configuration objects
        return (3, filename)      # Standard components/sequences

    sv_files.sort(key=compilation_priority)

    # Generate the package content
    output_path = os.path.join(source_dir, output_filename)
    with open(output_path, "w", encoding="utf-8") as f:
        # Header Guard & Boilerplate
        f.write(f"// ==================================================================\n")
        f.write(f"// Automatically generated by generate_soc_package.py\n")
        f.write(f"// ==================================================================\n\n")
        
        f.write(f"package {package_name};\n")
        f.write(f"  // Import standard UVM macros and package\n")
        f.write(f"  `include \"uvm_macros.svh\"\n")
        f.write(f"  import uvm_pkg::*;\n\n")
        
        f.write(f"  // ----------------------------------------------------------------\n")
        f.write(f"  // Component and Sequence Includes\n")
        f.write(f"  // ----------------------------------------------------------------\n")
        
        # Write individual `include lines
        for sv_file in sv_files:
            f.write(f"  `include \"{sv_file}\"\n")
            
        f.write(f"\nendpackage : {package_name}\n")

    print(f"Success! Generated '{output_path}' with {len(sv_files)} included files.")

if __name__ == "__main__":
    # Change '.' to your specific UVM agent/environment directory path if needed
    target_directory = "/home/harish/projects/SS/tb/" 
    generate_soc_package(target_directory)
