//----------------------------------------------------------------------
//   THIS IS AUTOMATICALLY GENERATED CODE
//   Generated by Mentor Graphics' Register Assistant UVM V2021.1 (Build 1)
//   UVM Register Kit version 1.1
//----------------------------------------------------------------------
// Project         : cdma_ral
// Unit            : axi_cdma_regblock_pkg
// File            : axi_cdma_regblock_pkg.sv
//----------------------------------------------------------------------
// Created by      : vidyasakar
// Creation Date   : 3/29/23 3:35 PM
//----------------------------------------------------------------------
// Title           : cdma_ral
//
// Description     : 
//
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// axi_cdma_regblock_pkg
//----------------------------------------------------------------------
package axi_cdma_regblock_pkg;

   import uvm_pkg::*;

   `include "uvm_macros.svh"

   /* DEFINE REGISTER CLASSES */



   //--------------------------------------------------------------------
   // Class: BTT
   // 
   //--------------------------------------------------------------------

   class BTT extends uvm_reg;
      `uvm_object_utils(BTT)

      uvm_reg_field Reserved; 
      rand uvm_reg_field BTT; 


      // Function: coverage
      // 
      covergroup cg_vals;
         Reserved	 : coverpoint Reserved.value[5:0];
         BTT	 : coverpoint BTT.value[25:0];
      endgroup



      // Function: new
      // 
      function new(string name = "BTT");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         Reserved = uvm_reg_field::type_id::create("Reserved");
         BTT = uvm_reg_field::type_id::create("BTT");

         Reserved.configure(this, 6, 26, "RO", 0, 6'b000000, 1, 0, 0);
         BTT.configure(this, 26, 0, "RW", 0, 26'b00000000000000000000000000, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: CDMA_CR
   // 
   //--------------------------------------------------------------------

   class CDMA_CR extends uvm_reg;
      `uvm_object_utils(CDMA_CR)

      rand uvm_reg_field IRQDelay; 
      rand uvm_reg_field IRQThreshold; 
      rand uvm_reg_field Reserved_2; 
      rand uvm_reg_field Err_IrqEn; 
      rand uvm_reg_field Dly_IrqEn; 
      rand uvm_reg_field IOC_IrqEn; 
      rand uvm_reg_field Reserved_1; 
      rand uvm_reg_field CyclicBDEnable; 
      rand uvm_reg_field KeyHoleWrite; 
      rand uvm_reg_field KeyHoleRead; 
      rand uvm_reg_field SGMode; 
      rand uvm_reg_field Reset; 
      uvm_reg_field TailPtrEn; 
      uvm_reg_field Reserved_0; 


      // Function: coverage
      // 
      covergroup cg_vals;
         IRQDelay	 : coverpoint IRQDelay.value[7:0];
         IRQThreshold	 : coverpoint IRQThreshold.value[7:0];
         Reserved_2	 : coverpoint Reserved_2.value[0];
         Err_IrqEn	 : coverpoint Err_IrqEn.value[0];
         Dly_IrqEn	 : coverpoint Dly_IrqEn.value[0];
         IOC_IrqEn	 : coverpoint IOC_IrqEn.value[0];
         Reserved_1	 : coverpoint Reserved_1.value[4:0];
         CyclicBDEnable	 : coverpoint CyclicBDEnable.value[0];
         KeyHoleWrite	 : coverpoint KeyHoleWrite.value[0];
         KeyHoleRead	 : coverpoint KeyHoleRead.value[0];
         SGMode	 : coverpoint SGMode.value[0];
         Reset	 : coverpoint Reset.value[0];
         TailPtrEn	 : coverpoint TailPtrEn.value[0];
         Reserved_0	 : coverpoint Reserved_0.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "CDMA_CR");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         IRQDelay = uvm_reg_field::type_id::create("IRQDelay");
         IRQThreshold = uvm_reg_field::type_id::create("IRQThreshold");
         Reserved_2 = uvm_reg_field::type_id::create("Reserved_2");
         Err_IrqEn = uvm_reg_field::type_id::create("Err_IrqEn");
         Dly_IrqEn = uvm_reg_field::type_id::create("Dly_IrqEn");
         IOC_IrqEn = uvm_reg_field::type_id::create("IOC_IrqEn");
         Reserved_1 = uvm_reg_field::type_id::create("Reserved_1");
         CyclicBDEnable = uvm_reg_field::type_id::create("CyclicBDEnable");
         KeyHoleWrite = uvm_reg_field::type_id::create("KeyHoleWrite");
         KeyHoleRead = uvm_reg_field::type_id::create("KeyHoleRead");
         SGMode = uvm_reg_field::type_id::create("SGMode");
         Reset = uvm_reg_field::type_id::create("Reset");
         TailPtrEn = uvm_reg_field::type_id::create("TailPtrEn");
         Reserved_0 = uvm_reg_field::type_id::create("Reserved_0");

         IRQDelay.configure(this, 8, 24, "RW", 0, 8'h00, 1, 1, 1);
         IRQThreshold.configure(this, 8, 16, "RW", 0, 8'h01, 1, 1, 1);
         Reserved_2.configure(this, 1, 15, "RO", 0, 1'b0, 1, 1, 0);
         Err_IrqEn.configure(this, 1, 14, "RW", 0, 1'b0, 1, 1, 0);
         Dly_IrqEn.configure(this, 1, 13, "RW", 0, 1'b0, 1, 1, 0);
         IOC_IrqEn.configure(this, 1, 12, "RW", 0, 1'b0, 1, 1, 0);
         Reserved_1.configure(this, 5, 7, "RO", 0, 5'b00000, 1, 1, 0);
         CyclicBDEnable.configure(this, 1, 6, "RW", 0, 1'b0, 1, 1, 0);
         KeyHoleWrite.configure(this, 1, 5, "RW", 0, 1'b0, 1, 1, 0);
         KeyHoleRead.configure(this, 1, 4, "RW", 0, 1'b0, 1, 1, 0);
         SGMode.configure(this, 1, 3, "RW", 0, 1'b0, 1, 1, 0);
         Reset.configure(this, 1, 2, "RW", 0, 1'b0, 1, 1, 0);
         TailPtrEn.configure(this, 1, 1, "RO", 0, 1'b1, 1, 0, 0);
         Reserved_0.configure(this, 1, 0, "RO", 0, 1'b0, 1, 0, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: CDMA_SR
   // 
   //--------------------------------------------------------------------

   class CDMA_SR extends uvm_reg;
      `uvm_object_utils(CDMA_SR)

      uvm_reg_field IRQDelaySts; 
      uvm_reg_field IRQThresholdSts; 
      uvm_reg_field Reserved_4; 
      uvm_reg_field Err_Irq; 
      uvm_reg_field Dly_Irq; 
      uvm_reg_field IOC_Irq; 
      uvm_reg_field Reserved_3; 
      uvm_reg_field SGDecErr; 
      uvm_reg_field SGSlvErr; 
      uvm_reg_field SGIntErr; 
      uvm_reg_field Reserved_2; 
      uvm_reg_field DMADecErr; 
      uvm_reg_field DMASlvErr; 
      uvm_reg_field DMAIntErr; 
      uvm_reg_field SGIncld; 
      uvm_reg_field Reserved_1; 
      uvm_reg_field Idle; 
      uvm_reg_field Reserved_0; 


      // Function: coverage
      // 
      covergroup cg_vals;
         IRQDelaySts	 : coverpoint IRQDelaySts.value[7:0];
         IRQThresholdSts	 : coverpoint IRQThresholdSts.value[7:0];
         Reserved_4	 : coverpoint Reserved_4.value[0];
         Err_Irq	 : coverpoint Err_Irq.value[0];
         Dly_Irq	 : coverpoint Dly_Irq.value[0];
         IOC_Irq	 : coverpoint IOC_Irq.value[0];
         Reserved_3	 : coverpoint Reserved_3.value[0];
         SGDecErr	 : coverpoint SGDecErr.value[0];
         SGSlvErr	 : coverpoint SGSlvErr.value[0];
         SGIntErr	 : coverpoint SGIntErr.value[0];
         Reserved_2	 : coverpoint Reserved_2.value[0];
         DMADecErr	 : coverpoint DMADecErr.value[0];
         DMASlvErr	 : coverpoint DMASlvErr.value[0];
         DMAIntErr	 : coverpoint DMAIntErr.value[0];
         SGIncld	 : coverpoint SGIncld.value[0];
         Reserved_1	 : coverpoint Reserved_1.value[0];
         Idle	 : coverpoint Idle.value[0];
         Reserved_0	 : coverpoint Reserved_0.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "CDMA_SR");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         IRQDelaySts = uvm_reg_field::type_id::create("IRQDelaySts");
         IRQThresholdSts = uvm_reg_field::type_id::create("IRQThresholdSts");
         Reserved_4 = uvm_reg_field::type_id::create("Reserved_4");
         Err_Irq = uvm_reg_field::type_id::create("Err_Irq");
         Dly_Irq = uvm_reg_field::type_id::create("Dly_Irq");
         IOC_Irq = uvm_reg_field::type_id::create("IOC_Irq");
         Reserved_3 = uvm_reg_field::type_id::create("Reserved_3");
         SGDecErr = uvm_reg_field::type_id::create("SGDecErr");
         SGSlvErr = uvm_reg_field::type_id::create("SGSlvErr");
         SGIntErr = uvm_reg_field::type_id::create("SGIntErr");
         Reserved_2 = uvm_reg_field::type_id::create("Reserved_2");
         DMADecErr = uvm_reg_field::type_id::create("DMADecErr");
         DMASlvErr = uvm_reg_field::type_id::create("DMASlvErr");
         DMAIntErr = uvm_reg_field::type_id::create("DMAIntErr");
         SGIncld = uvm_reg_field::type_id::create("SGIncld");
         Reserved_1 = uvm_reg_field::type_id::create("Reserved_1");
         Idle = uvm_reg_field::type_id::create("Idle");
         Reserved_0 = uvm_reg_field::type_id::create("Reserved_0");

         IRQDelaySts.configure	  (this, 8, 24, "RO", 0, 8'h00, 1, 0, 1);
         IRQThresholdSts.configure(this, 8, 16, "RO", 0, 8'h01, 1, 0, 1);
         Reserved_4.configure	  (this, 1, 15, "RO", 0,  1'b0, 1, 0, 0);
         Err_Irq.configure	  (this, 1, 14, "WC", 0,  1'b0, 1, 0, 0);
         Dly_Irq.configure	  (this, 1, 13, "WC", 0,  1'b0, 1, 0, 0);
         IOC_Irq.configure	  (this, 1, 12, "WC", 0,  1'b0, 1, 0, 0);
         Reserved_3.configure	  (this, 1, 11, "RO", 0,  1'b0, 1, 0, 0);
         SGDecErr.configure	  (this, 1, 10, "RO", 0,  1'b0, 1, 0, 0);
         SGSlvErr.configure	  (this, 1,  9, "RO", 0,  1'b0, 1, 0, 0);
         SGIntErr.configure	  (this, 1,  8, "RO", 0,  1'b0, 1, 0, 0);
         Reserved_2.configure	  (this, 1,  7, "RO", 0,  1'b0, 1, 0, 0);
         DMADecErr.configure	  (this, 1,  6, "RO", 0,  1'b0, 1, 0, 0);
         DMASlvErr.configure	  (this, 1,  5, "RO", 0,  1'b0, 1, 0, 0);
         DMAIntErr.configure	  (this, 1,  4, "RO", 0,  1'b0, 1, 0, 0);
         SGIncld.configure	  (this, 1,  3, "RO", 0,  1'b1, 1, 0, 0);
         Reserved_1.configure	  (this, 1,  2, "RO", 0,  1'b0, 1, 0, 0);
         Idle.configure		  (this, 1,  1, "RO", 0,  1'b1, 1, 0, 0);
         Reserved_0.configure	  (this, 1,  0, "RO", 0,  1'b0, 1, 0, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: CURDESC_PNTR
   // 
   //--------------------------------------------------------------------

   class CURDESC_PNTR extends uvm_reg;
      `uvm_object_utils(CURDESC_PNTR)

      rand uvm_reg_field CurrDescPntr; 
      uvm_reg_field Reserved; 


      // Function: coverage
      // 
      covergroup cg_vals;
         CurrDescPntr	 : coverpoint CurrDescPntr.value[25:0];
         Reserved	 : coverpoint Reserved.value[5:0];
      endgroup



      // Function: new
      // 
      function new(string name = "CURDESC_PNTR");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         CurrDescPntr = uvm_reg_field::type_id::create("CurrDescPntr");
         Reserved = uvm_reg_field::type_id::create("Reserved");

         CurrDescPntr.configure(this, 26, 6, "RW", 0, 26'b00000000000000000000000000, 1, 1, 0);
         Reserved.configure(this, 6, 0, "RO", 0, 6'b000000, 1, 0, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: CURDESC_PNTR_MSB
   // 
   //--------------------------------------------------------------------

   class CURDESC_PNTR_MSB extends uvm_reg;
      `uvm_object_utils(CURDESC_PNTR_MSB)

      rand uvm_reg_field CurrDescPntr; 


      // Function: coverage
      // 
      covergroup cg_vals;
         CurrDescPntr	 : coverpoint CurrDescPntr.value[31:0];
      endgroup



      // Function: new
      // 
      function new(string name = "CURDESC_PNTR_MSB");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         CurrDescPntr = uvm_reg_field::type_id::create("CurrDescPntr");

         CurrDescPntr.configure(this, 32, 0, "RW", 0, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: DA
   // 
   //--------------------------------------------------------------------

   class DA extends uvm_reg;
      `uvm_object_utils(DA)

      rand uvm_reg_field DA; 


      // Function: coverage
      // 
      covergroup cg_vals;
         DA	 : coverpoint DA.value[31:0];
      endgroup



      // Function: new
      // 
      function new(string name = "DA");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         DA = uvm_reg_field::type_id::create("DA");

         DA.configure(this, 32, 0, "RW", 0, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: DA_MSB
   // 
   //--------------------------------------------------------------------

   class DA_MSB extends uvm_reg;
      `uvm_object_utils(DA_MSB)

      rand uvm_reg_field DA; 


      // Function: coverage
      // 
      covergroup cg_vals;
         DA	 : coverpoint DA.value[31:0];
      endgroup



      // Function: new
      // 
      function new(string name = "DA_MSB");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         DA = uvm_reg_field::type_id::create("DA");

         DA.configure(this, 32, 0, "RW", 0, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: SA
   // 
   //--------------------------------------------------------------------

   class SA extends uvm_reg;
      `uvm_object_utils(SA)

      rand uvm_reg_field SA; 


      // Function: coverage
      // 
      covergroup cg_vals;
         SA	 : coverpoint SA.value[31:0];
      endgroup



      // Function: new
      // 
      function new(string name = "SA");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         SA = uvm_reg_field::type_id::create("SA");

         SA.configure(this, 32, 0, "RW", 0, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: SA_MSB
   // 
   //--------------------------------------------------------------------

   class SA_MSB extends uvm_reg;
      `uvm_object_utils(SA_MSB)

      rand uvm_reg_field SA; 


      // Function: coverage
      // 
      covergroup cg_vals;
         SA	 : coverpoint SA.value[31:0];
      endgroup



      // Function: new
      // 
      function new(string name = "SA_MSB");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         SA = uvm_reg_field::type_id::create("SA");

         SA.configure(this, 32, 0, "RW", 0, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: TAILDESC_PNTR
   // 
   //--------------------------------------------------------------------

   class TAILDESC_PNTR extends uvm_reg;
      `uvm_object_utils(TAILDESC_PNTR)

      rand uvm_reg_field TailDescPntr; 
      uvm_reg_field Reserved; 


      // Function: coverage
      // 
      covergroup cg_vals;
         TailDescPntr	 : coverpoint TailDescPntr.value[25:0];
         Reserved	 : coverpoint Reserved.value[5:0];
      endgroup



      // Function: new
      // 
      function new(string name = "TAILDESC_PNTR");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         TailDescPntr = uvm_reg_field::type_id::create("TailDescPntr");
         Reserved = uvm_reg_field::type_id::create("Reserved");

         TailDescPntr.configure(this, 26, 6, "RW", 0, 26'b00000000000000000000000000, 1, 1, 0);
         Reserved.configure(this, 6, 0, "RO", 0, 6'b000000, 1, 0, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: TAILDESC_PNTR_MSB
   // 
   //--------------------------------------------------------------------

   class TAILDESC_PNTR_MSB extends uvm_reg;
      `uvm_object_utils(TAILDESC_PNTR_MSB)

      rand uvm_reg_field TailDescPntr; 


      // Function: coverage
      // 
      covergroup cg_vals;
         TailDescPntr	 : coverpoint TailDescPntr.value[31:0];
      endgroup



      // Function: new
      // 
      function new(string name = "TAILDESC_PNTR_MSB");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         TailDescPntr = uvm_reg_field::type_id::create("TailDescPntr");

         TailDescPntr.configure(this, 32, 0, "RW", 0, 32'h00000000, 1, 1, 1);
      endfunction
   endclass




   /* BLOCKS */



   //--------------------------------------------------------------------
   // Class: cdma_reg_block
   // 
   //--------------------------------------------------------------------

   class cdma_reg_block extends uvm_reg_block;
      `uvm_object_utils(cdma_reg_block)

      rand CDMA_CR CDMA_CR_h; 
      rand CDMA_SR CDMA_SR_h; 
      rand CURDESC_PNTR CURDESC_PNTR_h; 
      rand CURDESC_PNTR_MSB CURDESC_PNTR_MSB_h; 
      rand TAILDESC_PNTR TAILDESC_PNTR_h; 
      rand TAILDESC_PNTR_MSB TAILDESC_PNTR_MSB_h; 
      rand SA SA_h; 
      rand SA_MSB SA_MSB_h; 
      rand DA DA_h; 
      rand DA_MSB DA_MSB_h; 
      rand BTT BTT_h; 

      uvm_reg_map bus_map; 


      // Function: new
      // 
      function new(string name = "cdma_reg_block");
         super.new(name, build_coverage(UVM_CVR_ALL));
      endfunction


      // Function: build
      // 
      virtual function void build();
         CDMA_CR_h = CDMA_CR::type_id::create("CDMA_CR_h");
         CDMA_CR_h.configure(this);
         CDMA_CR_h.build();
         CDMA_CR_h.add_hdl_path_slice("dmacr",0,CDMA_CR_h.get_n_bits());

         CDMA_SR_h = CDMA_SR::type_id::create("CDMA_SR_h");
         CDMA_SR_h.configure(this);
         CDMA_SR_h.build();
         CDMA_SR_h.add_hdl_path_slice("dmasr",0,CDMA_SR_h.get_n_bits());

         CURDESC_PNTR_h = CURDESC_PNTR::type_id::create("CURDESC_PNTR_h");
         CURDESC_PNTR_h.configure(this);
         CURDESC_PNTR_h.build();
         CURDESC_PNTR_h.add_hdl_path_slice("curdesc_lsb",0,CURDESC_PNTR_h.get_n_bits());

         CURDESC_PNTR_MSB_h = CURDESC_PNTR_MSB::type_id::create("CURDESC_PNTR_MSB_h");
         CURDESC_PNTR_MSB_h.configure(this);
         CURDESC_PNTR_MSB_h.build();
         CURDESC_PNTR_MSB_h.add_hdl_path_slice("curdesc_msb",0,CURDESC_PNTR_MSB_h.get_n_bits());

         TAILDESC_PNTR_h = TAILDESC_PNTR::type_id::create("TAILDESC_PNTR_h");
         TAILDESC_PNTR_h.configure(this);
         TAILDESC_PNTR_h.build();
         TAILDESC_PNTR_h.add_hdl_path_slice("taildesc_lsb",0,TAILDESC_PNTR_h.get_n_bits());

         TAILDESC_PNTR_MSB_h = TAILDESC_PNTR_MSB::type_id::create("TAILDESC_PNTR_MSB_h");
         TAILDESC_PNTR_MSB_h.configure(this);
         TAILDESC_PNTR_MSB_h.build();
         TAILDESC_PNTR_MSB_h.add_hdl_path_slice("taildesc_msb",0,TAILDESC_PNTR_MSB_h.get_n_bits());

         SA_h = SA::type_id::create("SA_h");
         SA_h.configure(this);
         SA_h.build();
         SA_h.add_hdl_path_slice("src_addr_lsb",0,SA_h.get_n_bits());
         
         SA_MSB_h = SA_MSB::type_id::create("SA_MSB_h");
         SA_MSB_h.configure(this);
         SA_MSB_h.build();
         SA_MSB_h.add_hdl_path_slice("src_addr_msb",0,SA_MSB_h.get_n_bits());
         
         DA_h = DA::type_id::create("DA_h");
         DA_h.configure(this);
         DA_h.build();
         DA_h.add_hdl_path_slice("dest_addr_lsb",0,DA_h.get_n_bits());

         DA_MSB_h = DA_MSB::type_id::create("DA_MSB_h");
         DA_MSB_h.configure(this);
         DA_MSB_h.build();
         DA_MSB_h.add_hdl_path_slice("dest_addr_msb",0,DA_MSB_h.get_n_bits());

         BTT_h = BTT::type_id::create("BTT_h");
         BTT_h.configure(this);
         BTT_h.build();
         BTT_h.add_hdl_path_slice("btt",0,BTT_h.get_n_bits());

         bus_map = create_map("bus_map", 'h0, 4, UVM_LITTLE_ENDIAN, 1);
         default_map = bus_map;

         bus_map.add_reg(CDMA_CR_h,		 'h0, "RW");
         bus_map.add_reg(CDMA_SR_h,		 'h4, "RW");
         bus_map.add_reg(CURDESC_PNTR_h,	 'h8, "RW");
         bus_map.add_reg(CURDESC_PNTR_MSB_h,	 'hc, "RW");
         bus_map.add_reg(TAILDESC_PNTR_h,	 'h10, "RW");
         bus_map.add_reg(TAILDESC_PNTR_MSB_h,	 'h14, "RW");
         bus_map.add_reg(SA_h,			 'h18, "RW");
         bus_map.add_reg(SA_MSB_h,		 'h1c, "RW");
         bus_map.add_reg(DA_h,			 'h20, "RW");
         bus_map.add_reg(DA_MSB_h,		 'h24, "RW");
         bus_map.add_reg(BTT_h,			 'h28, "RW");

         add_hdl_path("core_ibex_tb_top.dut.IPS_CORE.axi_cdma_0.U0.GEN_SG_MODE.I_SG_MODE_WRAP.I_HYBRID_REG_MODULE.I_REGISTER_BLOCK","RTL");

         lock_model();
      endfunction
   endclass


endpackage
