//----------------------------------------------------------------------------
// This file was generated by the Aldec, Inc. Register Generator.
// Version: 2023.04.112.8911
// Generated on: 2024-08-21 17:05
// Any modifications to this file will be lost if the code is regenerated.
//----------------------------------------------------------------------------


package axi_cdma_regblock_pkg;

    import uvm_pkg::*;
    `include "uvm_macros.svh"

    class CDMACR extends uvm_reg;
        `uvm_object_utils(CDMACR)

        uvm_reg_field ReserveD;
        uvm_reg_field TailPntrEn;
        rand uvm_reg_field Reset;
        rand uvm_reg_field SGMode;
        rand uvm_reg_field Key_Hole_Read;
        rand uvm_reg_field Key_Hole_Write;
        rand uvm_reg_field Cyclic_BD_Enable;
        uvm_reg_field Reserved;
        rand uvm_reg_field IOC_IrqEn;
        rand uvm_reg_field Dly_IrqEn;
        rand uvm_reg_field Err_IrqEn;
        uvm_reg_field RESERVED;
        rand uvm_reg_field IRQThreshold;
        rand uvm_reg_field IRQDelay;

        function new(string name = "CDMACR");
            super.new(name,32, UVM_NO_COVERAGE);
        endfunction

        virtual function void build();
            this.ReserveD = uvm_reg_field::type_id::create("ReserveD");
            this.ReserveD.configure(this, 1, 0, "RO", 0, 0, 1, 0, 1);
            this.TailPntrEn = uvm_reg_field::type_id::create("TailPntrEn");
            this.TailPntrEn.configure(this, 1, 1, "RO", 0, 1, 1, 0, 1);
            this.Reset = uvm_reg_field::type_id::create("Reset");
            this.Reset.configure(this, 1, 2, "RW", 0, 0, 1, 1, 1);
            this.SGMode = uvm_reg_field::type_id::create("SGMode");
            this.SGMode.configure(this, 1, 3, "RW", 0, 0, 1, 1, 1);
            this.Key_Hole_Read = uvm_reg_field::type_id::create("Key_Hole_Read");
            this.Key_Hole_Read.configure(this, 1, 4, "RW", 0, 0, 1, 1, 1);
            this.Key_Hole_Write = uvm_reg_field::type_id::create("Key_Hole_Write");
            this.Key_Hole_Write.configure(this, 1, 5, "RW", 0, 0, 1, 1, 1);
            this.Cyclic_BD_Enable = uvm_reg_field::type_id::create("Cyclic_BD_Enable");
            this.Cyclic_BD_Enable.configure(this, 1, 6, "RW", 0, 0, 1, 1, 1);
            this.Reserved = uvm_reg_field::type_id::create("Reserved");
            this.Reserved.configure(this, 5, 7, "RO", 0, 0, 1, 0, 1);
            this.IOC_IrqEn = uvm_reg_field::type_id::create("IOC_IrqEn");
            this.IOC_IrqEn.configure(this, 1, 12, "RW", 0, 0, 1, 1, 1);
            this.Dly_IrqEn = uvm_reg_field::type_id::create("Dly_IrqEn");
            this.Dly_IrqEn.configure(this, 1, 13, "RW", 0, 0, 1, 1, 1);
            this.Err_IrqEn = uvm_reg_field::type_id::create("Err_IrqEn");
            this.Err_IrqEn.configure(this, 1, 14, "RW", 0, 0, 1, 1, 1);
            this.RESERVED = uvm_reg_field::type_id::create("RESERVED");
            this.RESERVED.configure(this, 1, 15, "RO", 0, 0, 1, 0, 1);
            this.IRQThreshold = uvm_reg_field::type_id::create("IRQThreshold");
            this.IRQThreshold.configure(this, 8, 16, "RW", 0, 1, 1, 1, 1);
            this.IRQDelay = uvm_reg_field::type_id::create("IRQDelay");
            this.IRQDelay.configure(this, 8, 24, "RW", 0, 0, 1, 1, 1);
        endfunction
    endclass

    class CDMASR extends uvm_reg;
        `uvm_object_utils(CDMASR)

        uvm_reg_field ReserveD;
        uvm_reg_field Idle;
        uvm_reg_field ReservEd;
        uvm_reg_field SGIncld;
        uvm_reg_field DMAIntErr;
        uvm_reg_field DMASlvErr;
        uvm_reg_field DMADecErr;
        uvm_reg_field ResErved;
        uvm_reg_field SGIntErr;
        uvm_reg_field SGSlvErr;
        uvm_reg_field SGDecErr;
        uvm_reg_field Reserved;
        uvm_reg_field IOC_Irq;
        uvm_reg_field Dly_Irq;
        uvm_reg_field Err_Irq;
        uvm_reg_field RESERVED;
        uvm_reg_field IRQThresholdSts;
        uvm_reg_field IRQDelaySts;

        function new(string name = "CDMASR");
            super.new(name,32, UVM_NO_COVERAGE);
        endfunction

        virtual function void build();
            this.ReserveD = uvm_reg_field::type_id::create("ReserveD");
            this.ReserveD.configure(this, 1, 0, "RO", 0, 0, 1, 0, 1);
            this.Idle = uvm_reg_field::type_id::create("Idle");
            this.Idle.configure(this, 1, 1, "RO", 1, 0, 1, 0, 1);
            this.ReservEd = uvm_reg_field::type_id::create("ReservEd");
            this.ReservEd.configure(this, 1, 2, "RO", 0, 0, 1, 0, 1);
            this.SGIncld = uvm_reg_field::type_id::create("SGIncld");
            this.SGIncld.configure(this, 1, 3, "RO", 1, 0, 1, 0, 1);
            this.DMAIntErr = uvm_reg_field::type_id::create("DMAIntErr");
            this.DMAIntErr.configure(this, 1, 4, "RO", 1, 0, 1, 0, 1);
            this.DMASlvErr = uvm_reg_field::type_id::create("DMASlvErr");
            this.DMASlvErr.configure(this, 1, 5, "RO", 1, 0, 1, 0, 1);
            this.DMADecErr = uvm_reg_field::type_id::create("DMADecErr");
            this.DMADecErr.configure(this, 1, 6, "RO", 1, 0, 1, 0, 1);
            this.ResErved = uvm_reg_field::type_id::create("ResErved");
            this.ResErved.configure(this, 1, 7, "RO", 0, 0, 1, 0, 1);
            this.SGIntErr = uvm_reg_field::type_id::create("SGIntErr");
            this.SGIntErr.configure(this, 1, 8, "RO", 1, 0, 1, 0, 1);
            this.SGSlvErr = uvm_reg_field::type_id::create("SGSlvErr");
            this.SGSlvErr.configure(this, 1, 9, "RO", 1, 0, 1, 0, 1);
            this.SGDecErr = uvm_reg_field::type_id::create("SGDecErr");
            this.SGDecErr.configure(this, 1, 10, "RO", 1, 0, 1, 0, 1);
            this.Reserved = uvm_reg_field::type_id::create("Reserved");
            this.Reserved.configure(this, 1, 11, "RO", 0, 0, 1, 0, 1);
            this.IOC_Irq = uvm_reg_field::type_id::create("IOC_Irq");
            this.IOC_Irq.configure(this, 1, 12, "WC", 0, 0, 1, 0, 1);
            this.Dly_Irq = uvm_reg_field::type_id::create("Dly_Irq");
            this.Dly_Irq.configure(this, 1, 13, "WC", 0, 0, 1, 0, 1);
            this.Err_Irq = uvm_reg_field::type_id::create("Err_Irq");
            this.Err_Irq.configure(this, 1, 14, "WC", 0, 0, 1, 0, 1);
            this.RESERVED = uvm_reg_field::type_id::create("RESERVED");
            this.RESERVED.configure(this, 1, 15, "RO", 0, 0, 1, 0, 1);
            this.IRQThresholdSts = uvm_reg_field::type_id::create("IRQThresholdSts");
            this.IRQThresholdSts.configure(this, 8, 16, "RO", 1, 1, 1, 0, 1);
            this.IRQDelaySts = uvm_reg_field::type_id::create("IRQDelaySts");
            this.IRQDelaySts.configure(this, 8, 24, "RO", 1, 0, 1, 0, 1);
        endfunction
    endclass

    class CURDESC_PNT extends uvm_reg;
        `uvm_object_utils(CURDESC_PNT)

        uvm_reg_field Reserved;
        rand uvm_reg_field Current_Descriptor_Pointer;

        function new(string name = "CURDESC_PNT");
            super.new(name,32, UVM_NO_COVERAGE);
        endfunction

        virtual function void build();
            this.Reserved = uvm_reg_field::type_id::create("Reserved");
            this.Reserved.configure(this, 6, 0, "RO", 0, 0, 1, 0, 1);
            this.Current_Descriptor_Pointer = uvm_reg_field::type_id::create("Current_Descriptor_Pointer");
            this.Current_Descriptor_Pointer.configure(this, 26, 6, "RW", 1, 0, 1, 1, 1);
        endfunction
    endclass

    class CURDESC_PNT_MSB extends uvm_reg;
        `uvm_object_utils(CURDESC_PNT_MSB)

        rand uvm_reg_field Current_Descriptor_Pointer;

        function new(string name = "CURDESC_PNT_MSB");
            super.new(name,32, UVM_NO_COVERAGE);
        endfunction

        virtual function void build();
            this.Current_Descriptor_Pointer = uvm_reg_field::type_id::create("Current_Descriptor_Pointer");
            this.Current_Descriptor_Pointer.configure(this, 32, 0, "RW", 1, 0, 1, 1, 1);
        endfunction
    endclass

    class TAILDESC_PNT extends uvm_reg;
        `uvm_object_utils(TAILDESC_PNT)

        uvm_reg_field Reserved;
        rand uvm_reg_field Tail_Descriptor_Pointer;

        function new(string name = "TAILDESC_PNT");
            super.new(name,32, UVM_NO_COVERAGE);
        endfunction

        virtual function void build();
            this.Reserved = uvm_reg_field::type_id::create("Reserved");
            this.Reserved.configure(this, 6, 0, "RO", 0, 0, 1, 0, 1);
            this.Tail_Descriptor_Pointer = uvm_reg_field::type_id::create("Tail_Descriptor_Pointer");
            this.Tail_Descriptor_Pointer.configure(this, 26, 6, "RW", 1, 0, 1, 1, 0);
        endfunction
    endclass

    class TAILDESC_PNT_MSB extends uvm_reg;
        `uvm_object_utils(TAILDESC_PNT_MSB)

        rand uvm_reg_field Tail_Descriptor_Pointer;

        function new(string name = "TAILDESC_PNT_MSB");
            super.new(name,32, UVM_NO_COVERAGE);
        endfunction

        virtual function void build();
            this.Tail_Descriptor_Pointer = uvm_reg_field::type_id::create("Tail_Descriptor_Pointer");
            this.Tail_Descriptor_Pointer.configure(this, 32, 0, "RW", 1, 0, 1, 1, 1);
        endfunction
    endclass

    class SA extends uvm_reg;
        `uvm_object_utils(SA)

        rand uvm_reg_field SA;

        function new(string name = "SA");
            super.new(name,32, UVM_NO_COVERAGE);
        endfunction

        virtual function void build();
            this.SA = uvm_reg_field::type_id::create("SA");
            this.SA.configure(this, 32, 0, "RW", 0, 0, 1, 1, 1);
        endfunction
    endclass

    class SA_MSB extends uvm_reg;
        `uvm_object_utils(SA_MSB)

        rand uvm_reg_field SA;

        function new(string name = "SA_MSB");
            super.new(name,32, UVM_NO_COVERAGE);
        endfunction

        virtual function void build();
            this.SA = uvm_reg_field::type_id::create("SA");
            this.SA.configure(this, 32, 0, "RW", 0, 0, 1, 1, 1);
        endfunction
    endclass

    class DA extends uvm_reg;
        `uvm_object_utils(DA)

        rand uvm_reg_field DA;

        function new(string name = "DA");
            super.new(name,32, UVM_NO_COVERAGE);
        endfunction

        virtual function void build();
            this.DA = uvm_reg_field::type_id::create("DA");
            this.DA.configure(this, 32, 0, "RW", 0, 0, 1, 1, 1);
        endfunction
    endclass

    class DA_MSB extends uvm_reg;
        `uvm_object_utils(DA_MSB)

        rand uvm_reg_field DA;

        function new(string name = "DA_MSB");
            super.new(name,32, UVM_NO_COVERAGE);
        endfunction

        virtual function void build();
            this.DA = uvm_reg_field::type_id::create("DA");
            this.DA.configure(this, 32, 0, "RW", 0, 0, 1, 1, 1);
        endfunction
    endclass

    class BTT extends uvm_reg;
        `uvm_object_utils(BTT)

        rand uvm_reg_field BTT;
        uvm_reg_field Reserved;

        function new(string name = "BTT");
            super.new(name,32, UVM_NO_COVERAGE);
        endfunction

        virtual function void build();
            this.BTT = uvm_reg_field::type_id::create("BTT");
            this.BTT.configure(this, 26, 0, "RW", 0, 0, 1, 1, 1);
            this.Reserved = uvm_reg_field::type_id::create("Reserved");
            this.Reserved.configure(this, 6, 26, "RO", 0, 0, 1, 0, 1);
        endfunction
    endclass

    class cdma_reg_block extends uvm_reg_block;
        `uvm_object_utils(cdma_reg_block)

        covergroup bus_map_cg with function sample(uvm_reg_addr_t offset, bit is_read);
            option.per_instance = 1;
            OFFSET : coverpoint offset{
                bins cdmacr = {[0:3]};
                bins cdmasr = {[4:7]};
                bins curdesc_pnt = {[8:11]};
                bins curdesc_pnt_msb = {[12:15]};
                bins taildesc_pnt = {[16:19]};
                bins taildesc_pnt_msb = {[20:23]};
                bins sa = {[24:27]};
                bins sa_msb = {[28:31]};
                bins da = {[32:35]};
                bins da_msb = {[36:39]};
                bins btt = {[40:43]};
            }
            RW:coverpoint is_read{
                bins read = {1};
                bins write = {0};
            }
            OFFSET_RW : cross OFFSET, RW{
            }
        endgroup

        function new(string name = "reg_block");
            super.new(name, build_coverage(UVM_CVR_ADDR_MAP));
            if (has_coverage(UVM_CVR_ADDR_MAP))begin
                bus_map_cg = new();
                void'(set_coverage(UVM_CVR_ADDR_MAP));
            end
        endfunction

        rand CDMACR cdmacr;
        rand CDMASR cdmasr;
        rand CURDESC_PNT curdesc_pnt;
        rand CURDESC_PNT_MSB curdesc_pnt_msb;
        rand TAILDESC_PNT taildesc_pnt;
        rand TAILDESC_PNT_MSB taildesc_pnt_msb;
        rand SA sa;
        rand SA_MSB sa_msb;
        rand DA da;
        rand DA_MSB da_msb;
        rand BTT btt;

        uvm_reg_map bus_map;

        virtual function void build();
            cdmacr= CDMACR::type_id::create("cdmacr");
            cdmasr= CDMASR::type_id::create("cdmasr");
            curdesc_pnt= CURDESC_PNT::type_id::create("curdesc_pnt");
            curdesc_pnt_msb= CURDESC_PNT_MSB::type_id::create("curdesc_pnt_msb");
            taildesc_pnt= TAILDESC_PNT::type_id::create("taildesc_pnt");
            taildesc_pnt_msb= TAILDESC_PNT_MSB::type_id::create("taildesc_pnt_msb");
            sa= SA::type_id::create("sa");
            sa_msb= SA_MSB::type_id::create("sa_msb");
            da= DA::type_id::create("da");
            da_msb= DA_MSB::type_id::create("da_msb");
            btt= BTT::type_id::create("btt");

            cdmacr.configure(this, null, "");
            cdmasr.configure(this, null, "");
            curdesc_pnt.configure(this, null, "");
            curdesc_pnt_msb.configure(this, null, "");
            taildesc_pnt.configure(this, null, "");
            taildesc_pnt_msb.configure(this, null, "");
            sa.configure(this, null, "");
            sa_msb.configure(this, null, "");
            da.configure(this, null, "");
            da_msb.configure(this, null, "");
            btt.configure(this, null, "");

            cdmacr.build();
            cdmasr.build();
            curdesc_pnt.build();
            curdesc_pnt_msb.build();
            taildesc_pnt.build();
            taildesc_pnt_msb.build();
            sa.build();
            sa_msb.build();
            da.build();
            da_msb.build();
            btt.build();

            cdmacr.add_hdl_path_slice("dmacr",0,cdmacr.get_n_bits());
            cdmasr.add_hdl_path_slice("dmasr",0,cdmasr.get_n_bits());
            curdesc_pnt.add_hdl_path_slice("curdesc_lsb",0,curdesc_pnt.get_n_bits());
            curdesc_pnt_msb.add_hdl_path_slice("curdesc_msb",0,curdesc_pnt_msb.get_n_bits());
            taildesc_pnt.add_hdl_path_slice("taildesc_lsb",0,taildesc_pnt.get_n_bits());
            taildesc_pnt_msb.add_hdl_path_slice("taildesc_msb",0,taildesc_pnt_msb.get_n_bits());
            sa.add_hdl_path_slice("src_addr_lsb",0,sa.get_n_bits());
            sa_msb.add_hdl_path_slice("src_addr_msb",0,sa_msb.get_n_bits());
            da.add_hdl_path_slice("dest_addr_lsb",0,da.get_n_bits());
            da_msb.add_hdl_path_slice("dest_addr_msb",0,da_msb.get_n_bits());
            btt.add_hdl_path_slice("btt",0,btt.get_n_bits());

            bus_map = create_map("bus_map", 0, 4, UVM_LITTLE_ENDIAN, 1);

            this.bus_map.add_reg(cdmacr, 0, "RW", 0);
            this.bus_map.add_reg(cdmasr, 4, "RW", 0);
            this.bus_map.add_reg(curdesc_pnt, 8, "RW", 0);
            this.bus_map.add_reg(curdesc_pnt_msb, 12, "RW", 0);
            this.bus_map.add_reg(taildesc_pnt, 16, "RW", 0);
            this.bus_map.add_reg(taildesc_pnt_msb, 20, "RW", 0);
            this.bus_map.add_reg(sa, 24, "RW", 0);
            this.bus_map.add_reg(sa_msb, 28, "RW", 0);
            this.bus_map.add_reg(da, 32, "RW", 0);
            this.bus_map.add_reg(da_msb, 36, "RW", 0);
            this.bus_map.add_reg(btt, 40, "RW", 0);

            if (get_coverage(UVM_CVR_ADDR_MAP)) begin
                bus_map_cg.option.name = bus_map.get_full_name;
            end

                add_hdl_path("top.DUT.design_1_i.axi_cdma_0.U0.GEN_SG_MODE.I_SG_MODE_WRAP.I_HYBRID_REG_MODULE.I_REGISTER_BLOCK","RTL");
						
            lock_model();
        endfunction

        protected virtual function void  sample(uvm_reg_addr_t offset,bit is_read,uvm_reg_map map);
            if ((map != null) && get_coverage(UVM_CVR_ADDR_MAP)) begin
                if ( map == bus_map )
                    bus_map_cg.sample(offset, is_read);
            end
        endfunction
    endclass

endpackage
