onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group bram /top/axi4_bram_if/ACLK
add wave -noupdate -group bram /top/axi4_bram_if/ARESETn
add wave -noupdate -group bram /top/axi4_bram_if/ARID
add wave -noupdate -group bram /top/axi4_bram_if/ARADDR
add wave -noupdate -group bram /top/axi4_bram_if/ARLEN
add wave -noupdate -group bram /top/axi4_bram_if/ARSIZE
add wave -noupdate -group bram /top/axi4_bram_if/ARBURST
add wave -noupdate -group bram /top/axi4_bram_if/ARVALID
add wave -noupdate -group bram /top/axi4_bram_if/ARREADY
add wave -noupdate -group bram /top/axi4_bram_if/ARCACHE
add wave -noupdate -group bram /top/axi4_bram_if/ARLOCK
add wave -noupdate -group bram /top/axi4_bram_if/ARPROT
add wave -noupdate -group bram /top/axi4_bram_if/ARQOS
add wave -noupdate -group bram /top/axi4_bram_if/ARREGION
add wave -noupdate -group bram /top/axi4_bram_if/ARUSER
add wave -noupdate -group bram /top/axi4_bram_if/AWID
add wave -noupdate -group bram /top/axi4_bram_if/AWADDR
add wave -noupdate -group bram /top/axi4_bram_if/AWLEN
add wave -noupdate -group bram /top/axi4_bram_if/AWSIZE
add wave -noupdate -group bram /top/axi4_bram_if/AWBURST
add wave -noupdate -group bram /top/axi4_bram_if/AWVALID
add wave -noupdate -group bram /top/axi4_bram_if/AWREADY
add wave -noupdate -group bram /top/axi4_bram_if/AWCACHE
add wave -noupdate -group bram /top/axi4_bram_if/AWLOCK
add wave -noupdate -group bram /top/axi4_bram_if/AWPROT
add wave -noupdate -group bram /top/axi4_bram_if/AWQOS
add wave -noupdate -group bram /top/axi4_bram_if/AWREGION
add wave -noupdate -group bram /top/axi4_bram_if/AWUSER
add wave -noupdate -group bram /top/axi4_bram_if/BID
add wave -noupdate -group bram /top/axi4_bram_if/BRESP
add wave -noupdate -group bram /top/axi4_bram_if/BVALID
add wave -noupdate -group bram /top/axi4_bram_if/BREADY
add wave -noupdate -group bram /top/axi4_bram_if/BUSER
add wave -noupdate -group bram /top/axi4_bram_if/RID
add wave -noupdate -group bram /top/axi4_bram_if/RDATA
add wave -noupdate -group bram /top/axi4_bram_if/RLAST
add wave -noupdate -group bram /top/axi4_bram_if/RRESP
add wave -noupdate -group bram /top/axi4_bram_if/RVALID
add wave -noupdate -group bram /top/axi4_bram_if/RREADY
add wave -noupdate -group bram /top/axi4_bram_if/RUSER
add wave -noupdate -group bram /top/axi4_bram_if/WDATA
add wave -noupdate -group bram /top/axi4_bram_if/WSTRB
add wave -noupdate -group bram /top/axi4_bram_if/WLAST
add wave -noupdate -group bram /top/axi4_bram_if/WVALID
add wave -noupdate -group bram /top/axi4_bram_if/WREADY
add wave -noupdate -group bram /top/axi4_bram_if/WUSER
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/RID
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/RDATA
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/RRESP
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/RLAST
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/RVALID
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/RREADY
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/RUSER
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/BID
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/BRESP
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/BVALID
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/BREADY
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/BUSER
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/WDATA
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/WSTRB
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/WLAST
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/WVALID
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/WREADY
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/WUSER
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/AWADDR
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/AWBURST
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/AWCACHE
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/AWID
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/AWLEN
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/AWLOCK
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/AWPROT
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/AWQOS
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/AWREADY
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/AWREGION
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/AWSIZE
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/AWVALID
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/AWUSER
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/ARADDR
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/ARBURST
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/ARCACHE
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/ARID
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/ARLEN
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/ARLOCK
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/ARPROT
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/ARQOS
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/ARREADY
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/ARREGION
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/ARSIZE
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/ARVALID
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/ARUSER
add wave -noupdate -group bram /top/axi4_bram_if/axi4_mon_cb/axi4_mon_cb_event
add wave -noupdate -group lite_mem /top/mem_intf/ACLK
add wave -noupdate -group lite_mem /top/mem_intf/ARESETn
add wave -noupdate -group lite_mem /top/mem_intf/AWADDR
add wave -noupdate -group lite_mem /top/mem_intf/AWREADY
add wave -noupdate -group lite_mem /top/mem_intf/AWVALID
add wave -noupdate -group lite_mem /top/mem_intf/AWPROT
add wave -noupdate -group lite_mem /top/mem_intf/WDATA
add wave -noupdate -group lite_mem /top/mem_intf/WSTRB
add wave -noupdate -group lite_mem /top/mem_intf/WREADY
add wave -noupdate -group lite_mem /top/mem_intf/WVALID
add wave -noupdate -group lite_mem /top/mem_intf/BRESP
add wave -noupdate -group lite_mem /top/mem_intf/BREADY
add wave -noupdate -group lite_mem /top/mem_intf/BVALID
add wave -noupdate -group lite_mem /top/mem_intf/ARADDR
add wave -noupdate -group lite_mem /top/mem_intf/ARREADY
add wave -noupdate -group lite_mem /top/mem_intf/ARVALID
add wave -noupdate -group lite_mem /top/mem_intf/ARPROT
add wave -noupdate -group lite_mem /top/mem_intf/RDATA
add wave -noupdate -group lite_mem /top/mem_intf/RRESP
add wave -noupdate -group lite_mem /top/mem_intf/RREADY
add wave -noupdate -group lite_mem /top/mem_intf/RVALID
add wave -noupdate -group lite_mem /top/mem_intf/axil_drv_cb/RDATA
add wave -noupdate -group lite_mem /top/mem_intf/axil_drv_cb/RRESP
add wave -noupdate -group lite_mem /top/mem_intf/axil_drv_cb/RVALID
add wave -noupdate -group lite_mem /top/mem_intf/axil_drv_cb/BRESP
add wave -noupdate -group lite_mem /top/mem_intf/axil_drv_cb/BVALID
add wave -noupdate -group lite_mem /top/mem_intf/axil_drv_cb/WREADY
add wave -noupdate -group lite_mem /top/mem_intf/axil_drv_cb/AWREADY
add wave -noupdate -group lite_mem /top/mem_intf/axil_drv_cb/ARREADY
add wave -noupdate -group lite_mem /top/mem_intf/axil_drv_cb/ARESETn
add wave -noupdate -group lite_mem /top/mem_intf/axil_drv_cb/BREADY
add wave -noupdate -group lite_mem /top/mem_intf/axil_drv_cb/RREADY
add wave -noupdate -group lite_mem /top/mem_intf/axil_drv_cb/WDATA
add wave -noupdate -group lite_mem /top/mem_intf/axil_drv_cb/WSTRB
add wave -noupdate -group lite_mem /top/mem_intf/axil_drv_cb/WVALID
add wave -noupdate -group lite_mem /top/mem_intf/axil_drv_cb/AWADDR
add wave -noupdate -group lite_mem /top/mem_intf/axil_drv_cb/AWPROT
add wave -noupdate -group lite_mem /top/mem_intf/axil_drv_cb/AWVALID
add wave -noupdate -group lite_mem /top/mem_intf/axil_drv_cb/ARADDR
add wave -noupdate -group lite_mem /top/mem_intf/axil_drv_cb/ARPROT
add wave -noupdate -group lite_mem /top/mem_intf/axil_drv_cb/ARVALID
add wave -noupdate -group lite_mem /top/mem_intf/axil_drv_cb/axil_drv_cb_event
add wave -noupdate -group lite_mem /top/mem_intf/axil_mon_cb/RDATA
add wave -noupdate -group lite_mem /top/mem_intf/axil_mon_cb/RRESP
add wave -noupdate -group lite_mem /top/mem_intf/axil_mon_cb/RVALID
add wave -noupdate -group lite_mem /top/mem_intf/axil_mon_cb/RREADY
add wave -noupdate -group lite_mem /top/mem_intf/axil_mon_cb/BRESP
add wave -noupdate -group lite_mem /top/mem_intf/axil_mon_cb/BVALID
add wave -noupdate -group lite_mem /top/mem_intf/axil_mon_cb/BREADY
add wave -noupdate -group lite_mem /top/mem_intf/axil_mon_cb/WDATA
add wave -noupdate -group lite_mem /top/mem_intf/axil_mon_cb/WSTRB
add wave -noupdate -group lite_mem /top/mem_intf/axil_mon_cb/WVALID
add wave -noupdate -group lite_mem /top/mem_intf/axil_mon_cb/WREADY
add wave -noupdate -group lite_mem /top/mem_intf/axil_mon_cb/AWADDR
add wave -noupdate -group lite_mem /top/mem_intf/axil_mon_cb/AWPROT
add wave -noupdate -group lite_mem /top/mem_intf/axil_mon_cb/AWVALID
add wave -noupdate -group lite_mem /top/mem_intf/axil_mon_cb/AWREADY
add wave -noupdate -group lite_mem /top/mem_intf/axil_mon_cb/ARADDR
add wave -noupdate -group lite_mem /top/mem_intf/axil_mon_cb/ARPROT
add wave -noupdate -group lite_mem /top/mem_intf/axil_mon_cb/ARVALID
add wave -noupdate -group lite_mem /top/mem_intf/axil_mon_cb/ARREADY
add wave -noupdate -group lite_mem /top/mem_intf/axil_mon_cb/ARESETn
add wave -noupdate -group lite_mem /top/mem_intf/axil_mon_cb/axil_mon_cb_event
add wave -noupdate -group cpu /top/axil_riscv_if/ACLK
add wave -noupdate -group cpu /top/axil_riscv_if/ARESETn
add wave -noupdate -group cpu /top/axil_riscv_if/AWADDR
add wave -noupdate -group cpu /top/axil_riscv_if/AWREADY
add wave -noupdate -group cpu /top/axil_riscv_if/AWVALID
add wave -noupdate -group cpu /top/axil_riscv_if/AWPROT
add wave -noupdate -group cpu /top/axil_riscv_if/WDATA
add wave -noupdate -group cpu /top/axil_riscv_if/WSTRB
add wave -noupdate -group cpu /top/axil_riscv_if/WREADY
add wave -noupdate -group cpu /top/axil_riscv_if/WVALID
add wave -noupdate -group cpu /top/axil_riscv_if/BRESP
add wave -noupdate -group cpu /top/axil_riscv_if/BREADY
add wave -noupdate -group cpu /top/axil_riscv_if/BVALID
add wave -noupdate -group cpu /top/axil_riscv_if/ARADDR
add wave -noupdate -group cpu /top/axil_riscv_if/ARREADY
add wave -noupdate -group cpu /top/axil_riscv_if/ARVALID
add wave -noupdate -group cpu /top/axil_riscv_if/ARPROT
add wave -noupdate -group cpu /top/axil_riscv_if/RDATA
add wave -noupdate -group cpu /top/axil_riscv_if/RRESP
add wave -noupdate -group cpu /top/axil_riscv_if/RREADY
add wave -noupdate -group cpu /top/axil_riscv_if/RVALID
add wave -noupdate -group cpu /top/axil_riscv_if/axil_drv_cb/RDATA
add wave -noupdate -group cpu /top/axil_riscv_if/axil_drv_cb/RRESP
add wave -noupdate -group cpu /top/axil_riscv_if/axil_drv_cb/RVALID
add wave -noupdate -group cpu /top/axil_riscv_if/axil_drv_cb/BRESP
add wave -noupdate -group cpu /top/axil_riscv_if/axil_drv_cb/BVALID
add wave -noupdate -group cpu /top/axil_riscv_if/axil_drv_cb/WREADY
add wave -noupdate -group cpu /top/axil_riscv_if/axil_drv_cb/AWREADY
add wave -noupdate -group cpu /top/axil_riscv_if/axil_drv_cb/ARREADY
add wave -noupdate -group cpu /top/axil_riscv_if/axil_drv_cb/ARESETn
add wave -noupdate -group cpu /top/axil_riscv_if/axil_drv_cb/BREADY
add wave -noupdate -group cpu /top/axil_riscv_if/axil_drv_cb/RREADY
add wave -noupdate -group cpu /top/axil_riscv_if/axil_drv_cb/WDATA
add wave -noupdate -group cpu /top/axil_riscv_if/axil_drv_cb/WSTRB
add wave -noupdate -group cpu /top/axil_riscv_if/axil_drv_cb/WVALID
add wave -noupdate -group cpu /top/axil_riscv_if/axil_drv_cb/AWADDR
add wave -noupdate -group cpu /top/axil_riscv_if/axil_drv_cb/AWPROT
add wave -noupdate -group cpu /top/axil_riscv_if/axil_drv_cb/AWVALID
add wave -noupdate -group cpu /top/axil_riscv_if/axil_drv_cb/ARADDR
add wave -noupdate -group cpu /top/axil_riscv_if/axil_drv_cb/ARPROT
add wave -noupdate -group cpu /top/axil_riscv_if/axil_drv_cb/ARVALID
add wave -noupdate -group cpu /top/axil_riscv_if/axil_drv_cb/axil_drv_cb_event
add wave -noupdate -group cpu /top/axil_riscv_if/axil_mon_cb/RDATA
add wave -noupdate -group cpu /top/axil_riscv_if/axil_mon_cb/RRESP
add wave -noupdate -group cpu /top/axil_riscv_if/axil_mon_cb/RVALID
add wave -noupdate -group cpu /top/axil_riscv_if/axil_mon_cb/RREADY
add wave -noupdate -group cpu /top/axil_riscv_if/axil_mon_cb/BRESP
add wave -noupdate -group cpu /top/axil_riscv_if/axil_mon_cb/BVALID
add wave -noupdate -group cpu /top/axil_riscv_if/axil_mon_cb/BREADY
add wave -noupdate -group cpu /top/axil_riscv_if/axil_mon_cb/WDATA
add wave -noupdate -group cpu /top/axil_riscv_if/axil_mon_cb/WSTRB
add wave -noupdate -group cpu /top/axil_riscv_if/axil_mon_cb/WVALID
add wave -noupdate -group cpu /top/axil_riscv_if/axil_mon_cb/WREADY
add wave -noupdate -group cpu /top/axil_riscv_if/axil_mon_cb/AWADDR
add wave -noupdate -group cpu /top/axil_riscv_if/axil_mon_cb/AWPROT
add wave -noupdate -group cpu /top/axil_riscv_if/axil_mon_cb/AWVALID
add wave -noupdate -group cpu /top/axil_riscv_if/axil_mon_cb/AWREADY
add wave -noupdate -group cpu /top/axil_riscv_if/axil_mon_cb/ARADDR
add wave -noupdate -group cpu /top/axil_riscv_if/axil_mon_cb/ARPROT
add wave -noupdate -group cpu /top/axil_riscv_if/axil_mon_cb/ARVALID
add wave -noupdate -group cpu /top/axil_riscv_if/axil_mon_cb/ARREADY
add wave -noupdate -group cpu /top/axil_riscv_if/axil_mon_cb/ARESETn
add wave -noupdate -group cpu /top/axil_riscv_if/axil_mon_cb/axil_mon_cb_event
add wave -noupdate -group lite_intc /top/lite_intc_if/aclk
add wave -noupdate -group lite_intc /top/lite_intc_if/areset_n
add wave -noupdate -group lite_intc /top/lite_intc_if/axi_awaddr
add wave -noupdate -group lite_intc /top/lite_intc_if/axi_awvalid
add wave -noupdate -group lite_intc /top/lite_intc_if/axi_awready
add wave -noupdate -group lite_intc /top/lite_intc_if/axi_wdata
add wave -noupdate -group lite_intc /top/lite_intc_if/axi_wstrb
add wave -noupdate -group lite_intc /top/lite_intc_if/axi_wvalid
add wave -noupdate -group lite_intc /top/lite_intc_if/axi_wready
add wave -noupdate -group lite_intc /top/lite_intc_if/axi_bresp
add wave -noupdate -group lite_intc /top/lite_intc_if/axi_bvalid
add wave -noupdate -group lite_intc /top/lite_intc_if/axi_bready
add wave -noupdate -group lite_intc /top/lite_intc_if/axi_araddr
add wave -noupdate -group lite_intc /top/lite_intc_if/axi_arvalid
add wave -noupdate -group lite_intc /top/lite_intc_if/axi_arready
add wave -noupdate -group lite_intc /top/lite_intc_if/axi_rdata
add wave -noupdate -group lite_intc /top/lite_intc_if/axi_rresp
add wave -noupdate -group lite_intc /top/lite_intc_if/axi_rvalid
add wave -noupdate -group lite_intc /top/lite_intc_if/axi_rready
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_drv_cb/axi_rready
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_drv_cb/axi_rvalid
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_drv_cb/axi_rresp
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_drv_cb/axi_rdata
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_drv_cb/axi_arready
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_drv_cb/axi_arvalid
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_drv_cb/axi_araddr
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_drv_cb/axi_bvalid
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_drv_cb/axi_bresp
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_drv_cb/axi_bready
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_drv_cb/axi_wready
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_drv_cb/axi_wvalid
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_drv_cb/axi_wstrb
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_drv_cb/axi_wdata
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_drv_cb/axi_awready
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_drv_cb/axi_awvalid
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_drv_cb/axi_awaddr
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_drv_cb/axi4_lite_drv_cb_event
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_mon_cb/axi_rready
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_mon_cb/axi_rvalid
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_mon_cb/axi_rresp
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_mon_cb/axi_rdata
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_mon_cb/axi_arready
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_mon_cb/axi_arvalid
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_mon_cb/axi_araddr
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_mon_cb/axi_bvalid
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_mon_cb/axi_bresp
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_mon_cb/axi_bready
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_mon_cb/axi_wready
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_mon_cb/axi_wvalid
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_mon_cb/axi_wstrb
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_mon_cb/axi_wdata
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_mon_cb/axi_awready
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_mon_cb/axi_awvalid
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_mon_cb/axi_awaddr
add wave -noupdate -group lite_intc /top/lite_intc_if/axi4_lite_mon_cb/axi4_lite_mon_cb_event
add wave -noupdate -group cdma_introut /top/dut/IPS_CORE/cdma_introut_0
add wave -noupdate -group intc /top/intc_if/intc_procss_clk
add wave -noupdate -group intc /top/intc_if/intc_procss_rst
add wave -noupdate -group intc /top/intc_if/intc_intr
add wave -noupdate -group intc /top/intc_if/intc_irq
add wave -noupdate -group intc /top/intc_if/intc_interface_driver_cb/intc_irq
add wave -noupdate -group intc /top/intc_if/intc_interface_driver_cb/intc_intr
add wave -noupdate -group intc /top/intc_if/intc_interface_driver_cb/intc_interface_driver_cb_event
add wave -noupdate -group intc /top/intc_if/intc_interface_monitor_cb/intc_irq
add wave -noupdate -group intc /top/intc_if/intc_interface_monitor_cb/intc_intr
add wave -noupdate -group intc /top/intc_if/intc_interface_monitor_cb/intc_interface_monitor_cb_event
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/aclk
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/areset_n
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/awid
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/awaddr
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/awlen
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/awburst
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/awsize
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/awvalid
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/awready
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/bid
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/bresp
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/bvalid
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/bready
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/wdata
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/wstrobe
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/wlast
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/wvalid
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/wready
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/awlock
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/awprot
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/awqos
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/awregion
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/awcache
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/arid
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/araddr
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/arlen
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/arburst
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/arsize
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/arvalid
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/arready
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/rid
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/rresp
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/rdata
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/rlast
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/rvalid
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/rready
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/arlock
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/arprot
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/arqos
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/arregion
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/arcache
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/cdma_introut
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/arvalid
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/arsize
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/arregion
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/arready
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/arqos
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/arprot
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/arlock
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/arlen
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/arid
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/arcache
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/arburst
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/araddr
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/wvalid
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/wstrobe
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/wready
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/wlast
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/wdata
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/rvalid
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/rresp
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/rready
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/rlast
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/rid
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/rdata
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/bvalid
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/bresp
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/bready
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/bid
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/awvalid
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/awsize
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/awregion
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/awready
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/awqos
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/awprot
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/awlock
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/awlen
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/awid
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/awcache
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/awburst
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/awaddr
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_drv_cb/mas_drv_cb_event
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/arcache
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/arregion
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/arqos
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/arprot
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/arlock
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/rready
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/rvalid
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/rlast
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/rdata
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/rresp
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/rid
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/arready
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/arvalid
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/arsize
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/arburst
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/arlen
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/araddr
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/arid
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/awcache
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/awregion
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/awqos
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/awprot
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/awlock
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/wready
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/wvalid
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/wlast
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/wstrobe
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/wdata
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/bready
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/bvalid
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/bresp
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/bid
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/awready
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/awvalid
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/awsize
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/awburst
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/awlen
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/awaddr
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/awid
add wave -noupdate -group lite_cdma /top/cdma_reg_intf/mas_mon_cb/mas_mon_cb_event
add wave -noupdate -group cdma_intr /top/cdma_interrupt_intf/aclk
add wave -noupdate -group cdma_intr /top/cdma_interrupt_intf/interrupt_out
add wave -noupdate -group cdma_intr /top/cdma_interrupt_intf/int_mon_cb/interrupt_out
add wave -noupdate -group cdma_intr /top/cdma_interrupt_intf/int_mon_cb/int_mon_cb_event
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/aclk
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/areset_n
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/awid
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/awaddr
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/awlen
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/awburst
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/awsize
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/awvalid
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/awready
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/bid
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/bresp
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/bvalid
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/bready
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/wdata
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/wstrobe
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/wlast
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/wvalid
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/wready
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/awlock
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/awprot
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/awqos
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/awregion
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/awcache
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/arid
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/araddr
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/arlen
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/arburst
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/arsize
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/arvalid
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/arready
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/rid
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/rresp
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/rdata
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/rlast
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/rvalid
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/rready
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/arlock
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/arprot
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/arqos
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/arregion
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/arcache
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/wvalid
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/wstrobe
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/wready
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/wlast
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/wdata
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/bvalid
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/bid
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/bresp
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/bready
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/awvalid
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/awsize
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/awregion
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/awready
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/awqos
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/awprot
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/awlock
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/awlen
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/awid
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/awcache
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/awburst
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/awaddr
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/rvalid
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/rresp
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/rready
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/rlast
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/rid
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/rdata
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/arvalid
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/arsize
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/arregion
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/arready
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/arqos
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/arid
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/arprot
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/arlock
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/arlen
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/arcache
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/arburst
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/araddr
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_drv_cb/slv_drv_cb_event
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/awcache
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/awregion
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/awqos
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/awprot
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/awlock
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/wready
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/wvalid
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/wlast
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/wstrobe
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/wdata
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/bready
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/bvalid
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/bresp
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/bid
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/awready
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/awvalid
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/awsize
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/awburst
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/awlen
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/awaddr
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/awid
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/arcache
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/arregion
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/arqos
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/arprot
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/arlock
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/rvalid
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/rlast
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/rdata
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/rresp
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/rid
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/arready
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/rready
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/arvalid
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/arsize
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/arburst
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/arlen
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/araddr
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/arid
add wave -noupdate -group cdma_datamover /top/cdma_data_mov_intf/slv_mon_cb/slv_mon_cb_event
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/aclk
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/areset_n
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/awid
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/awaddr
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/awlen
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/awburst
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/awsize
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/awvalid
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/awready
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/bid
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/bresp
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/bvalid
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/bready
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/wdata
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/wstrobe
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/wlast
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/wvalid
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/wready
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/awlock
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/awprot
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/awqos
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/awregion
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/awcache
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/arid
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/araddr
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/arlen
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/arburst
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/arsize
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/arvalid
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/arready
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/rid
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/rresp
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/rdata
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/rlast
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/rvalid
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/rready
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/arlock
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/arprot
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/arqos
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/arregion
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/arcache
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/wvalid
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/wstrobe
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/wready
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/wlast
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/wdata
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/bvalid
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/bid
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/bresp
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/bready
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/awvalid
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/awsize
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/awregion
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/awready
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/awqos
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/awprot
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/awlock
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/awlen
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/awid
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/awcache
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/awburst
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/awaddr
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/rvalid
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/rresp
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/rready
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/rlast
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/rid
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/rdata
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/arvalid
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/arsize
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/arregion
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/arready
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/arqos
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/arid
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/arprot
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/arlock
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/arlen
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/arcache
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/arburst
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/araddr
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_drv_cb/slv_drv_cb_event
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/awcache
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/awregion
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/awqos
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/awprot
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/awlock
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/wready
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/wvalid
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/wlast
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/wstrobe
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/wdata
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/bready
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/bvalid
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/bresp
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/bid
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/awready
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/awvalid
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/awsize
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/awburst
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/awlen
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/awaddr
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/awid
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/arcache
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/arregion
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/arqos
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/arprot
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/arlock
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/rvalid
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/rlast
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/rdata
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/rresp
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/rid
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/arready
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/rready
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/arvalid
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/arsize
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/arburst
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/arlen
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/araddr
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/arid
add wave -noupdate -group cdma_sg /top/cdma_sg_intf/slv_mon_cb/slv_mon_cb_event
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {2573345 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 233
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {9559657 ps}
